[package]
name = "rapid_recorder"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic_float = "1.1.0"
crossbeam = "0.8.4"
dashmap = "6.1.0"
env_logger = "0.11.8"
flurry = "0.5.2"
log = "0.4.27"
parking_lot = "0.12.4"
rayon = "1.11.0"
